# Generated by Django 5.0.4 on 2024-04-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
